name: Deploy Next.js SSR to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

      # 1. 코드 checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Save SSH private key
        run: |
          printf "%s\n" "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Check secrets
        run: |
          echo "HOST: ${{ secrets.EC2_HOST }}"
          echo "USER: ${{ secrets.EC2_USER }}"

     # 2. 파일업로드 기능 추가로 변경
      - name: Upload project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: private_key.pem
          source:  |
	    package.json
	    package-lock.json
	    public/
	    pages/
	    .next/
	    styles/
          target: "${{ secrets.APP_PATH }}/"    
    
      # 3. SSH로 EC2에서 빌드 및 서버 재시작
      - name: SSH and build/start Next.js
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: private_key.pem
          script: |
            cd ${{ secrets.APP_PATH }}
            npm install
            npm run build
            pm2 stop all || true
            pm2 start npm --name "nextjs" -- start

