name: Deploy Next.js SSR to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Save SSH private key
        run: |
          printf "%s\n" "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Check secrets
        run: |
          echo "HOST: ${{ secrets.EC2_HOST }}"
          echo "USER: ${{ secrets.EC2_USER }}"
      - name: Check key file permissions
        run: |
          ls -l private_key.pem
          cat private_key.pem | head -n 5

      - name: Upload project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: private_key.pem
          source: "./*"
          target: "${{ secrets.APP_PATH }}/"

      - name: SSH and build/start Next.js
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: private_key.pem
          script: |
            cd ${{ secrets.APP_PATH }}
            npm install
            npm run build
            pm2 stop all || true
            pm2 start npm --name "nextjs" -- start


